[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2021"

[dependencies]
cached = "0.46.1"
itertools = "0.12.0"
ndarray = "0.15.6"
ndarray-linalg = { version = "0.16.0", features = ["openblas-static"] }
nom = "7.1.3"
petgraph = "0.6.4"
rand = "0.8.5"
rstest = "0.18.2"
